### ISSUE TITLE
Error on `docker-compose up frontend`

### ISSUE THREAD

**Issue by BradyPlanden** [galv-team/galv-frontend#10]
**Describe the bug**
Currently, `docker-compose up frontend` results in the following error:

![image](https://github.com/galv-team/galv-frontend/assets/55357039/ea4409d4-f7df-41b7-8946-3c70dcb8288a)

**To Reproduce**
Run `docker-compose up frontend` 

**Additional context**
Hardware: M3 Macbook Pro, using Colima as container runtimes

**Comment by BradyPlanden** [comment]
That did the trick 👍 

Should `--build` be added to the development command on the README?

**Comment by mjaquiery** [comment]
Good call.

**Comment by mjaquiery** [comment]
Should be closed by https://github.com/galv-team/galv-frontend/commit/836439a029648c5d76710b3089a3bc51cedb1c24
